# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c13e9ff2d163ecb6e7b76babe4bd937d7c1a5cf918d85c8801b47fc50a445d8716084096696a1d234d7a2a4ffac91fe0f239980f3b411e178bfe05d72b6db9b

test:
  secret_key_base: 955ad2366a906ec6cbf69fd5a133d40fc86d362ff6d8917f839608def35e9337642855252cfd88b2a588245c2f2399f6d31037bb10eb62d50f1c726da211f20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
